export const RECIEVE_GIPHY_RESPONSE = 'RECIEVE_GIPHY_RESPONSE';
export const RECIEVE_FILTER_UPDATE = 'RECIEVE_FILTER_UPDATE';
export const RECIEVE_OFFSET_UPDATE = 'RECIEVE_OFFSET_UPDATE';
export const RECIEVE_MODAL_UPDATE = 'RECIEVE_MODAL_UPDATE';